package uz.faceguard.app.data.repository

import androidx.room.withTransaction
import javax.inject.Inject
import javax.inject.Singleton
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import uz.faceguard.app.data.db.FaceGuardDatabase
import uz.faceguard.app.data.db.ScheduleAppTargetEntity
import uz.faceguard.app.data.db.ScheduleDao
import uz.faceguard.app.domain.schedule.ScheduleDraft
import uz.faceguard.app.domain.schedule.ScheduleRepository
import uz.faceguard.app.domain.schedule.ScheduleRule

/**
 * Phase 5 Step 2: Room-backed schedule persistence.
 *
 * Room entities never leave this layer; the domain sees only [ScheduleRule]. Every operation
 * names its account and child, and nothing here can act on a schedule id alone.
 *
 * Writes that span both tables — a schedule *and* its affected-app rows — go through
 * [FaceGuardDatabase.withTransaction], the same Room transaction boundary the project already
 * uses (`RoomUsageAccountingTransaction`). So a create/update is never observable as new
 * metadata with the old target set, and a delete never leaves orphaned target rows. There are
 * no foreign keys in this database, matching the rest of the schema, so that cleanup is done
 * explicitly here rather than by cascade.
 *
 * This class is persistence only: no clock beyond the `createdAt`/`updatedAt` bookkeeping the
 * other repositories also do, no schedule evaluation, no policy and no runtime.
 */
@Singleton
class ScheduleRepositoryImpl @Inject constructor(
    private val database: FaceGuardDatabase,
    private val dao: ScheduleDao,
) : ScheduleRepository {

    override fun observeSchedules(accountId: Long, childId: Long): Flow<List<ScheduleRule>> =
        dao.observeSchedules(accountId, childId).map { rows -> rows.map { it.toDomainSchedule() } }

    override suspend fun schedules(accountId: Long, childId: Long): List<ScheduleRule> =
        dao.schedules(accountId, childId).map { it.toDomainSchedule() }

    override suspend fun schedule(accountId: Long, childId: Long, scheduleId: Long): ScheduleRule? =
        dao.schedule(accountId, childId, scheduleId)?.toDomainSchedule()

    override suspend fun create(
        accountId: Long,
        childId: Long,
        draft: ScheduleDraft,
        targetPackages: Set<String>,
    ): ScheduleRule {
        requirePositiveScope(accountId, childId)
        // Build the rule once to run the domain's own validation *before* anything is written
        // (blank name, unimplemented action, invalid window/days all fail here). The id used
        // for that check is discarded; the real one is generated by the insert below.
        draft.withId(VALIDATION_ONLY_ID)
        val targets = validateTargets(targetPackages)

        val now = System.currentTimeMillis()
        return database.withTransaction {
            val newId = dao.insert(draft.toEntity(accountId, childId, id = 0L, createdAt = now, updatedAt = now))
            check(newId > 0L) { "insert did not generate a schedule id" }
            insertTargets(accountId, childId, newId, targets)
            draft.withId(newId)
        }
    }

    override suspend fun update(
        accountId: Long,
        childId: Long,
        schedule: ScheduleRule,
        targetPackages: Set<String>,
    ): ScheduleRule? {
        requirePositiveScope(accountId, childId)
        val targets = validateTargets(targetPackages)
        val now = System.currentTimeMillis()

        return database.withTransaction {
            // The WHERE clause carries accountId + childId + id, so another child's row is
            // untouched and reported as "not ours" instead of being modified.
            val updated = dao.update(
                accountId = accountId,
                childId = childId,
                scheduleId = schedule.id,
                name = schedule.name,
                mode = schedule.mode.name,
                enabled = schedule.enabled,
                startMinuteOfDay = schedule.window.startMinuteOfDay,
                endMinuteOfDay = schedule.window.endMinuteOfDay,
                daysMask = schedule.days.mask,
                priority = schedule.priority,
                action = schedule.action.name,
                updatedAt = now,
            )
            if (updated == 0) return@withTransaction null

            dao.deleteTargets(accountId, childId, schedule.id)
            insertTargets(accountId, childId, schedule.id, targets)
            schedule
        }
    }

    override suspend fun delete(accountId: Long, childId: Long, scheduleId: Long) {
        requirePositiveScope(accountId, childId)
        database.withTransaction {
            dao.deleteTargets(accountId, childId, scheduleId)
            dao.delete(accountId, childId, scheduleId)
        }
    }

    override suspend fun deleteAllForChild(accountId: Long, childId: Long) {
        requirePositiveScope(accountId, childId)
        database.withTransaction {
            dao.deleteTargetsForChild(accountId, childId)
            dao.deleteForChild(accountId, childId)
        }
    }

    override fun observeTargetPackages(accountId: Long, childId: Long, scheduleId: Long): Flow<List<String>> =
        dao.observeTargetPackages(accountId, childId, scheduleId)

    override suspend fun targetPackages(accountId: Long, childId: Long, scheduleId: Long): List<String> =
        dao.targetPackages(accountId, childId, scheduleId)

    override suspend fun replaceTargetPackages(
        accountId: Long,
        childId: Long,
        scheduleId: Long,
        packageNames: Set<String>,
    ) {
        requirePositiveScope(accountId, childId)
        val targets = validateTargets(packageNames)
        database.withTransaction {
            // Refuse to file targets under a schedule this account + child does not own, so a
            // wrong id cannot create rows no schedule will ever reference.
            if (dao.schedule(accountId, childId, scheduleId) == null) return@withTransaction
            dao.deleteTargets(accountId, childId, scheduleId)
            insertTargets(accountId, childId, scheduleId, targets)
        }
    }

    private suspend fun insertTargets(
        accountId: Long,
        childId: Long,
        scheduleId: Long,
        packageNames: List<String>,
    ) {
        if (packageNames.isEmpty()) return
        dao.insertTargets(
            packageNames.map { ScheduleAppTargetEntity(accountId, childId, scheduleId, it) },
        )
    }

    private fun requirePositiveScope(accountId: Long, childId: Long) {
        require(accountId > 0L) { "accountId must be positive, was $accountId" }
        require(childId > 0L) { "childId must be positive, was $childId" }
    }

    /**
     * A `Set` already makes duplicates impossible, so the only thing left to reject is a
     * blank identifier. The sorted list is what is actually stored, which keeps the rows (and
     * therefore any later read) deterministic.
     */
    private fun validateTargets(packageNames: Set<String>): List<String> {
        packageNames.forEach { require(it.isNotBlank()) { "packageName must not be blank" } }
        return packageNames.sorted()
    }

    private companion object {
        /** Only used to run the domain's validation on a draft before its real id exists. */
        const val VALIDATION_ONLY_ID = 1L
    }
}
